# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Alternative Prelude with numeric and logic expressions typed bottom-up"
HOMEPAGE="https://github.com/michalkonecny/mixed-types-num"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/convertible-1.1.1.0:=[profile?]
	>=dev-haskell/hspec-2.1:=[profile?]
	>=dev-haskell/hspec-smallcheck-0.3:=[profile?]
	>=dev-haskell/quickcheck-2.7:2=[profile?]
	>=dev-haskell/smallcheck-1.1:=[profile?] <dev-haskell/smallcheck-1.2:=[profile?]
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"
