# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Haskell interface to GMP"
HOMEPAGE="https://code.mathr.co.uk/hgmp"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="
        >=dev-lang/ghc-7.6.1:= <dev-lang/ghc-8.3:=
"
DEPEND="${RDEPEND}
        test? ( >=dev-haskell/hspec-1.3
                >=dev-haskell/hunit-1.2 )
"
